collections:
  team_members:
    people: true

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


remote_theme: "mmistakes/minimal-mistakes@4.14.1"
